// Renaming and exporting all repository classes:
module.exports = {
    ServiceContacts: require('./service_contacts'),
    ClientDetailsProtocol: require('./client_details_protocol'),
    ClientDetails: require('./client_details'),
    ServiceDetails: require('./service_details'),
    User:require('./user'),
    UserInfo: require('./user_info'),
    UserEduPersonEntitlement: require('./user_edu_person_entitlement'),
    ServiceMultiValued: require('./service_multi_valued'),
    ClientMultiValued: require('./client_multi_valued'),
    ServicePetitionDetails: require('./service_petition_details'),
    ClientPetitionDetails: require('./client_petition_details'),
    Service: require('./service'),
    ClientRepository: require('./client'),
    ServiceState: require('./service_state'),
    Petition: require('./petition'),
    ServiceList: require('./service_list'),
    UserRole: require('./user_role'),
    Tokens: require('./tokens'),
    Group: require('./group'),
    Invitation: require('./invitation'),
    Tenants: require('./tenants'),
    DeployerAgents: require('./deployer_agent'),
    DeploymentTasks: require('./deployment_tasks'),
    ClientErrors: require('./client_errors'),
    Organizations: require('./organizations'),
    BannerAlerts: require('./banner_alerts'),
    ServiceTags: require('./service_tags')
};
